import React from "react";
import "./style.scss";

function Termandconditions() {
  return (
    <div className="termandconditions">
      <div className="term_heading">
        PRIVACY AND DATA PROTECTION POLICY (THE “POLICY”)
      </div>
      <div className="term_body">Last updated - 20 March 2023</div>
      <div className="term_body">
        [NOTE: This Policy is subject to further changes and will be amended
        from time to time. Please refer to the latest version before providing
        any personal data to us.]
      </div>
      <div className="term_body">Updated on: 20 March 2023</div>
      <div className="term_subtitle"> 1 . PRIVACY POLICY STATEMENT</div>
      <div className="term_body">
        <ul>
          <li>
            Nexsphere Holdings Pte Ltd., (the “Company”, “we”, “our” or “us”)
            respects Your legal rights to personal data protection when we
            collect, transfer, store, or access Your personal data.
          </li>
        </ul>
      </div>

      <div className="term_body">
        <ul>
          <li>
            This Privacy Policy Statement outlines the Company’ practices in
            relation to the collection, storage, use, processing and disclosure
            of personal data (as defined under the Personal Data Protection Act
            2012 (“PDPA”) through Our website at https://www.nexsphere.xyz (the
            “Website”).
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            By visiting, accessing, or using the Website, you (“User”, “You”, or
            “Your”) have indicated that You are at least eighteen (18) years
            old, have the legal capacity to consent to this Policy, and to agree
            to be bound by the policies and practices of this Policy in their
            entirety. This Policy sets out:
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ol>
          <li>
            The personal data being collected and the sources from which we
            collect such personal data;
          </li>
          <li>
            The purposes for collection, use and disclosure of personal data;
          </li>
          <li>Disclosure of personal data;</li>
          <li>
            Care of personal data (accuracy, protection, retention and
            transfer); and
          </li>
          <li>
            The process by which we receive and respond to any feedback that may
            arise regarding the collection, storage, use, processing, and
            disclosure of personal data.
          </li>
        </ol>
      </div>
      <div className="term_body">
        <ul>
          <li>
            This Policy may be amended from time to time and we will provide
            notice of such amendments by posting the revised Terms on the
            Website (and changing the “Updated on” date reflected in the top
            left-hand corner of this page).
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        2 . COLLECTION OF PERSONAL AND OTHER INFORMATION
      </div>
      <div className="term_body">
        <ul>
          <li>
            Non-Personal Data: If the User uses the Website, the User consents
            to allowing the Company to collect information about the User’s
            activities and trends through the Website. Such information may
            include (a) Device Information: Information that is automatically
            collected about Your device, such as, but not limited to, Your
            browser’s name and technical information about Your means of
            connection to the Website, in particular hardware, operating system,
            browser, among other similar information; (b) Location Information:
            Information that is automatically collected via analytics systems
            providers to determine your location, including Your IP address
            and/or domain name and any external page that referred you to us;
            (c) Log Information: Information that is generated by your use of
            the Website that is automatically collected and stored in our server
            logs. This may include, but is not limited to, device-specific
            information, location information, system activity and any internal
            and external information related to the Website that you visit; and
            (d) Account Information: Information that is generated by your
            account activity on the Website including, but not limited to,
            purchase activity, trading activity, deposits, withdrawals, and
            account balances. We aggregate this information to provide
            statistical data about our users' browsing actions and patterns, and
            do not identify individuals. 
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The User expressly agrees and acknowledges that the Company shall
            collect and store the User’s personal information, including but not
            limited to:
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ol>
          <li>the User’s full name,</li>
          <li>
            contact information such as your email address, residential address,
            and phone numbers,
          </li>
          <li>your current occupation and employment history,</li>
          <li>source of wealth and funds, and</li>
          <li>
            additional information or documentation that may be requested at the
            discretion of our compliance team (“User Information”).
          </li>
        </ol>
      </div>
      <div className="term_body">
        <ul>
          <li>
            Such User Information may come within the meaning of “personal data”
            as defined in the PDPA and as used in this Policy. The User
            acknowledges that Your User Information may be used by the Company
            to provide services and features targeted at the User, that are most
            likely to meet the User’s needs, and to customize and improve the
            Website and the experiences of You and other users of the Website
            (but these other users will not see or have access to Your User
            Information).
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The user is aware that all information pertaining to the User
            collected by the Company, whether or not directly provided by the
            User to the Company (via the Website or otherwise), including but
            not limited to personal correspondence such as emails or letters,
            instructions from the User relating to the Services, or
            communications between the User and other users, as well as
            information that You provide to us in correspondence with respect to
            ongoing customer support may be collected and compiled by the
            Company and You hereby expressly consent to the same.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            Cookies: The Company collects data by way of ‘cookies’. Cookies are
            small data files which are sent to the User’s browser from the
            Website and are stored on the User’s computer or device (hard
            drive). The cookies shall not provide access to data in the User’s
            computer or device (hard drive), such as email address or any other
            data that can be traced to the User personally. The data collected
            by way of cookies will allow Us to administer the Website and
            provide a tailored and user-friendly service to the Users.
            Information collected from cookies is used by Us to evaluate the
            effectiveness of the Website, analyze trends, and administer the
            Website. The information collected from cookies allows the Company
            to determine such things as which parts of the Website are most
            visited and difficulties our visitors may experience in accessing
            the Website. With this knowledge, the Company aims to improve the
            quality of the User’s experience on the Website by recognising and
            delivering the most desired features and information. In addition to
            cookies, the Company may also use a technology known as web bugs or
            clear gifs, which are typically stored in emails to help confirm
            receipt of, and response to, the emails sent by the Company and to
            provide the User with a personalized experience while accessing the
            Website. You agree to the use of cookies by continuing to use the
            Website and any platform operated by the Company.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The cookies shall enable the Users to access certain features or
            services of the Website. Most web browsers and devices can be set to
            notify when a User receives a cookie or to prevent cookies from
            being sent; if the User accepts such features, it may limit the
            functionality that the Company can provide when a User visits the
            Website.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            We may also collect or otherwise be provided with User Information
            about You from third parties whose websites you visit or whose
            services you use, including as social media platforms, where You may
            have authorized such websites and platforms to collect and share
            your User Information.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">3 . USE OF THE INFORMATION COLLECTED</div>
      <div className="term_body">
        <ul>
          <li>We may use the User Information to:</li>
        </ul>
      </div>
      <div className="term_body">
        <ol>
          <li>
            Provide the User with the use of the Website and the services
            offered on the Website, including customer support by the Company;
          </li>
          <li>
            Optimize and enhance the Website or any websites or platform
            operated by the Company or its affiliates, for all users, or for You
            specifically;
          </li>
          <li>
            Conduct anti-fraud, anti-money laundering, countering of terrorist
            financing, and identity verification and authentication
            Know-Your-Customer checks (You authorize Us to share Your
            information with Our third-party service providers, when applicable,
            who may also conduct their own searches about You);
          </li>
          <li>
            Monitor the usage of the Website, and conduct automated and manual
            security checks of Our service; and
          </li>
          <li>
            Create aggregated and anonymised reporting data about the Company.
          </li>
        </ol>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The Company will handle personal data appropriately, in line with
            the circumstances and in accordance with applicable law in India,
            including the PDPA. If any intended use of personal data will go
            beyond the purposes envisioned during collection, the Company will
            notify Users of the new purpose(s) and seek consent to use their
            personal data for such purpose(s).
          </li>
        </ul>
      </div>
      <div className="term_subtitle"> 4 . SUBMISSIONS</div>
      <div className="term_body">
        <ul>
          <li>
            We cannot agree to obligations of confidentiality or nondisclosure
            with regard to any unsolicited information the User submits to Us,
            regardless of the method or medium chosen. By submitting unsolicited
            information or materials to Us or the Company’s service providers,
            You or anyone acting on Your behalf, agree that any such information
            or materials will not be considered confidential or proprietary.
          </li>
        </ul>
      </div>

      <div className="term_body">
        <ul>
          <li>
            We do not provide any facility for sending or receiving private or
            confidential electronic communications. You should not use the
            Website to transmit any communication for which You intend only for
            You and the intended recipient(s) to read. Notice is hereby given
            that all messages and other content entered using the Website can
            and may be read by Us, regardless of whether We are the intended
            recipients of such messages. Nevertheless, access to messages and
            other content will be accessible only by the authorized personnel of
            the Company and its service providers that reasonably need such
            access.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        5 . SECURITY AND RETENTION OF PERSONAL INFORMATION
      </div>
      <div className="term_body">
        <ul>
          <li>
            We protect the personal data in Our possession or under Our control
            by making reasonable and practical security arrangements to protect
            the User’s personal information from unauthorized access,
            collection, use, disclosure, copying, modification, disposal or
            similar. Unfortunately, however, no data transmission over the
            internet or data storage system can be guaranteed to be completely
            secure.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The User agrees and acknowledges that the above-mentioned measures
            do not guarantee absolute protection and by accessing the Website,
            the User agrees to assume all risks associated with disclosure of
            personal information arising due to breach of firewalls and secure
            server software.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The Company undertakes to review the security measures from time to
            time in light of new and relevant legal and technical developments.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The User is aware that personal data may continue to be stored and
            retained by the Company for the period necessary to carry out the
            purposes outlined in this Policy unless a longer retention is
            required under applicable law or until it is no longer necessary for
            any other legal or Company purposes (whichever is later).
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        6 . DISCLOSURE OF PERSONAL INFORMATION
      </div>
      <div className="term_body">
        <ul>
          <li>
            In general, the Company will not disclose personal data except in
            accordance with the following:
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            <ol>
              <li>
                In general, the Company will not disclose personal data except
                in accordance with the following:
              </li>
              <li>where the User has consented; or</li>
              <li>
                where permitted under the PDPA or other applicable law or;
              </li>
              <li>
                if required by applicable law, including the reporting of
                suspicious transactions to the authorities in any jurisdiction.
              </li>
            </ol>
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            You should be aware that Ethereum and other cryptocurrencies are not
            necessarily truly anonymous.  Generally, anyone can see the balance,
            transaction history, and public keys of any address on the Ethereum
            blockchain. We, and any others who can match Your public address to
            other information about You, may be able to identify You from a
            blockchain transaction. This is because, in some circumstances,
            information published on a block chain (such as Your public key and
            IP address) can be correlated with information that we and others
            may have. This may be the case even if We, or they, were not
            involved in the blockchain transaction. Furthermore, by using data
            analysis techniques on a given blockchain, it may be possible to
            identify other information about You. As part of Our security,
            anti-fraud, anti-money laundering and/or identity verification and
            authentication checks, the Company may conduct such analysis to
            collect and process such information about You. You acknowledge and
            agree to allow Us to perform such practices.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        7 . THIRD PARTY USER EXPERIENCE IMPROVEMENT SERVICES
      </div>
      <div className="term_body">
        <ul>
          <li>
            You should be aware that Ethereum and other cryptocurrencies are not
            necessarily truly anonymous.  Generally, anyone can see the balance,
            transaction history, and public keys of any address on the Ethereum
            blockchain. We, and any others who can match Your public address to
            other information about You, may be able to identify You from a
            blockchain transaction. This is because, in some circumstances,
            information published on a block chain (such as Your public key and
            IP address) can be correlated with information that we and others
            may have. This may be the case even if We, or they, were not
            involved in the blockchain transaction. Furthermore, by using data
            analysis techniques on a given blockchain, it may be possible to
            identify other information about You. As part of Our security,
            anti-fraud, anti-money laundering and/or identity verification and
            authentication checks, the Company may conduct such analysis to
            collect and process such information about You. You acknowledge and
            agree to allow Us to perform such practices.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            A User’s relationship with these third parties and their services
            and tools is independent of the User’s relationship with the
            Company. These third parties may allow the User to permit / restrict
            the information that is collected and it may be in the User’s
            interest to individually restrict or enable such data collections. 
            The place of processing depends on each third party service provider
            and the User may wish to check the privacy policy of each of these
            service providers to identify how much data is shared and why.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            A User’s relationship with these third parties and their services
            and tools is independent of the User’s relationship with the
            Company. These third parties may allow the User to permit / restrict
            the information that is collected and it may be in the User’s
            interest to individually restrict or enable such data collections. 
            The place of processing depends on each third party service provider
            and the User may wish to check the privacy policy of each of these
            service providers to identify how much data is shared and why.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        8 . THIRD PARTY USER EXPERIENCE IMPROVEMENT SERVICES
      </div>
      <div className="term_body">
        <ul>
          <li>
            The Company may use third party authentication services. In such
            cases, We may be privy to, granted access to and / or store, certain
            data available with these third parties for registration and
            identification purposes.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The place of processing depends on each third party service provider
            and You may wish to check the privacy policy of each of these
            service providers to identify how much data is shared and why.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">9 . THIRD PARTY LINKS</div>
      <div className="term_body">
        <ul>
          <li>
            We may, at our discretion, include third party products or services
            on the Website that are not operated by Us. These third party sites
            have separate and independent privacy policies. We have no control
            over, and therefore assume no responsibility or liability for the
            content and activities of these linked websites. We strongly advise
            You to review the privacy policy of every site you visit. 
          </li>
        </ul>
      </div>
      <div className="term_subtitle"> 10 . THIRD PARTY STORAGE</div>
      <div className="term_body">
        <ul>
          <li>
            The Company and the Website may use international web hosting
            facilities and cloud server services which are maintained in
            accordance with tight security standards.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        11 . TRANSFER OF PERSONAL DATA OUTSIDE India
      </div>
      <div className="term_body">
        <ul>
          <li>
            We may store and process your personal information in data centers
            around the world wherever the service providers are located. As
            such, we may transfer your personal data outside India. Such
            transfers are undertaken in accordance with applicable laws and
            regulatory obligations.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">12 . COMPANY TRANSITIONS</div>
      <div className="term_body">
        <ul>
          <li>
            The User is aware that in the event the Company goes through a
            transition, such as a merger, acquisition by another organisation,
            or sale of all or a portion of its assets, the Users’ personal data
            might be among the assets transferred as a result of the Company
            transition.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        13 . ACCESS TO AND CORRECTION OF INFORMATION
      </div>
      <div className="term_body">
        <ul>
          <li>
            Under the terms of the PDPA, You have the right to ascertain whether
            We hold Your accurate and current information, and the right to
            access and correct Your personal data. You may exercise this right
            by contacting Us at the contact details provided below.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            When handling a data access or correction request, We check the
            identity of the requesting party to ensure that he or she is the
            person legally entitled to make such request. A reasonable fee may
            be charged to cover our administrative costs incurred for complying
            with Your data access request.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">
        14 . WITHDRAWAL OF CONSENT TO USE YOUR PERSONAL DATA
      </div>
      <div className="term_body">
        <ul>
          <li>
            You may withdraw Your consent for Us to use Your personal data at
            any time by contacting Us as directed below. We shall stop using
            Your personal data and ensure that the parties to whom We
            transferred Your personal data in accordance with paragraphs 5, 6,
            10, 11 and 12, will comply with Your request. If You only wish to
            stop receiving marketing or promotional materials and information
            from Us, please contact Us as indicated below.
          </li>
        </ul>
      </div>
      <div className="term_subtitle">15 . UPDATE TO THIS POLICY</div>
      <div className="term_body">
        <ul>
          <li>
            The Company reserves its right to revise, modify and update this
            Policy at any time, without prior notice, at the sole discretion of
            the Company.
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            The Company undertakes to notify the Users on the Website in the
            event the Policy is revised and make available the revised Policy.
          </li>
        </ul>
      </div>
      <div className="term_subtitle"> 16 . CONTACT AND ENQUIRIES</div>
      <div className="term_body">
        <ul>
          <li>
            Please send any questions or requests in relation to the Policy to:
            privacy@nexsphere.xyz
          </li>
        </ul>
      </div>
      <div className="term_body">
        <ul>
          <li>
            To facilitate any request in respect of your personal data, You
            should indicate “PDPA Request” in your email or other communication
            to us.
          </li>
        </ul>
      </div>
    </div>
  );
}

export default Termandconditions;
